import { FamousSong } from "./types";

export const FAMOUS_SONGS: FamousSong[] = [
  // === EPIC TAMIL CINEMA HITS (1-20) ===
  {
    number: 1,
    title: "Maruthamalai Mamaniye Murugaiya",
    authorOrArtist: "Kannadasan / Madurai Somu (Movie: Deivam)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A legendary high-pitch classical masterpiece celebrating the deity of Maruthamalai Hills structure.",
  },
  {
    number: 2,
    title: "Pazham Neeyappa",
    authorOrArtist: "Kannadasan / K.B. Sundarambal (Movie: Thiruvilaiyadal)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "The earth-shaking high-register classical rendition representing Lord Murugan as the fruit of absolute wisdom.",
  },
  {
    number: 3,
    title: "Thirupparankundrathil Nee Sirithal",
    authorOrArtist: "Kannadasan / S. Janaki & P.B. Sreenivas (Movie: Kandhan Karunai)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "An evergreen lyrical duet visualizing the scenic divine hills of Thirupparankundram as nature's absolute smile.",
  },
  {
    number: 4,
    title: "Aarupadai Veedu Konda",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan (Movie: Kandhan Karunai)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A soaring and rhythmic traversal of the six sacred mountain headquarters of Lord Skanda.",
  },
  {
    number: 5,
    title: "Aarumugamana Porul",
    authorOrArtist: "Kannadasan / Soolamangalam Rajalakshmi (Movie: Kandhan Karunai)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A soft, educational, and classical explanation of the six-fold cosmic mystery of Lord Murugan.",
  },
  {
    number: 6,
    title: "Kundrathile Kumarannukku Kondattam",
    authorOrArtist: "Kannadasan / T.M. Soundararajan (Movie: Deivam)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A joyous, infectious folk-classical fusion expressing the jubilant festivals on Lord Kumaran's sacred hills.",
  },
  {
    number: 7,
    title: "Thiruchenduril Por Purindhu",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan (Movie: Deivam)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "An epic martial-devotional track describing the battle on the seashore of Tiruchendur against arrogance.",
  },
  {
    number: 8,
    title: "Gnana Pazham Pizhindhu",
    authorOrArtist: "Kannadasan / K.B. Sundarambal (Movie: Thiruvilaiyadal)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A deeply soulful and classical solo exploring the symbolic meaning behind the divine fruit of knowledge.",
  },
  {
    number: 9,
    title: "Murugane Senthil Muthukumaraney",
    authorOrArtist: "Traditional / P. Susheela (Movie: Kandhan Karunai)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A sweet, prayerful coastal track invoking the protection of Kandan, the lord of Tiruchendur.",
  },
  {
    number: 10,
    title: "Vetrivel Veeravel",
    authorOrArtist: "Ilaiyaraaja / S.P. Balasubrahmanyam (Movie: Thoongathe Thambi Thoongathe)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A modern, highly energetic, and upbeat anthem shouting out the protective victory call of the Spear.",
  },
  {
    number: 11,
    title: "Thamizhukku Niramundu",
    authorOrArtist: "Kannadasan / T.M. Soundararajan (Movie: Thiruvarul)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "An ingenious composition analyzing how Lord Murugan represents the color, life, and grammar of Tamil language.",
  },
  {
    number: 12,
    title: "Vel Muruganukku Moimbal",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan (Movie: Kandhan Karunai)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A massive, powerful choral and solo chant illustrating the infinite strength of Lord Skanda's Spear.",
  },
  {
    number: 13,
    title: "Kurinjiyile Poo Malarnthu",
    authorOrArtist: "Kannadasan / T.M. Soundararajan (Movie: Kandhan Karunai)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "Poetically compares the rare Kurinji mountain blossom to the glorious physical form and grace of Murugan.",
  },
  {
    number: 14,
    title: "Arul Tharum Deivam",
    authorOrArtist: "Traditional / T.M. Soundararajan (Movie: Thiruvarul)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A highly moving cinematic request showing absolute trust and devotion to the lord who never deserts his seekers.",
  },
  {
    number: 15,
    title: "Aarumugam Kaanapattaal",
    authorOrArtist: "Traditional / K.B. Sundarambal (Movie: Sri Valli)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "Declares that the mere sight of Lord Murugan's six faces instantly clears away the dark clouds of mortal worries.",
  },
  {
    number: 16,
    title: "Kandhan Enral",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan (Movie: Sri Valli)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A lyrical masterclass exploring the divine etymologies and sounds behind the word 'Kandhan'.",
  },
  {
    number: 17,
    title: "Velan Varuvan",
    authorOrArtist: "Traditional / P. Susheela (Movie: Sri Valli)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "A cheerful, hopeful song showing absolute certainty that the savior with the Spear will arrive in time.",
  },
  {
    number: 18,
    title: "Kandanukku Velanukku",
    authorOrArtist: "Traditional / T.M. Soundararajan (Movie: Deiva Thirumanangal)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "Celebrates the grand and beautiful cosmic wedding ceremonies of Lord Murugan to Valli and Devayanai.",
  },
  {
    number: 19,
    title: "Solla Solla Inikkudhada",
    authorOrArtist: "Kannadasan / T.M. Soundararajan (Movie: Kandhan Karunai)",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "Describes the sweet, euphoric feeling that fills the devotee's physical body when chanting the name of Murugan.",
  },
  {
    number: 20,
    title: "Muthai Tharu Pathi",
    authorOrArtist: "Saint Arunagirinathar / Played in multiple epics",
    genre: "cinema_hits",
    genreLabel: "Epic Cinema Hits",
    details: "The supreme opening hymn of Thiruppugazh, written at Tiruvannamalai temple tower, featured in classic cinema.",
    localSongId: "muthai-tharu",
  },

  // === THE DEVOTIONAL ERA OF T.M. SOUNDARARAJAN (TMS) (21-40) ===
  {
    number: 21,
    title: "Ullam Uruguthaiya",
    authorOrArtist: "Andavan Pichai / Sung by T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "The most famous devotional recording in modern Tamil history, bringing tears of deep surrender to millions.",
  },
  {
    number: 22,
    title: "Azhagendra Sollukku",
    authorOrArtist: "Kannadasan / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Declares that the word 'Azhagu' (absolute beauty) is another form and name of Lord Kumaran.",
  },
  {
    number: 23,
    title: "Mannanalum Thiruchenduril",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A passionate wish to remain forever at the coastal temple of Tiruchendur, even if reduced to a speck of beach sand.",
  },
  {
    number: 24,
    title: "Karpanai Endralum",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Proclaims that even imagining Kandan's sweet form for a single second fills the mind with absolute quietude.",
  },
  {
    number: 25,
    title: "Muruga Endrazhaikava",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A classic which asks: 'Should I summon you as Muruga, Kanda, or Velava? How can my single tongue describe you?'",
  },
  {
    number: 26,
    title: "Karpagacholaiyile",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Captures the cooling, forest-like tranquility found in the high garden trails of Swamimalai Shrine.",
  },
  {
    number: 27,
    title: "Unnai Paadatha Naavum",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A rigorous devotional piece that values a human life and voice only if they are dedicated to praising Kandan.",
  },
  {
    number: 28,
    title: "Velava Velava",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A highly rhythmic, martial-cadence hymn to arouse the inner willpower symbolized by the Sacred Spear.",
  },
  {
    number: 29,
    title: "Pulli Mayil Vel Muruganu",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A cheerful, upbeat track dedicated to the spotted cosmic peacock that flies carrying the Lord of the Spear.",
  },
  {
    number: 30,
    title: "Senthoor Andavanin",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Adoring the gorgeous posture of the Lord of Tiruchendur as He looks out over the roaring blue sea.",
  },
  {
    number: 31,
    title: "Vel Muruga Maal Maruga",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A joyous track celebrating Murugan's kinship as the beloved nephew of Lord Maha Vishnu.",
  },
  {
    number: 32,
    title: "Deivam Endral Athu",
    authorOrArtist: "Kannadasan / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A deep philosophical track identifying the supreme deity as the universal source of all clean love and beauty.",
  },
  {
    number: 33,
    title: "Kandan Thiruneer",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Sings of the high-vibrational healing power of the sacred white ash (Vibhuti) of Lord Murugan of Palani.",
  },
  {
    number: 34,
    title: "Adiva Mayile",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "An upbeat folk-style call welcoming the blue bird of victory to dance in front of the shrine.",
  },
  {
    number: 35,
    title: "Kathiravan Ezhuthal",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "A glorious morning waking-up Suprabhatam style song greeting the sun rise over the temples of Skanda.",
  },
  {
    number: 36,
    title: "Shanmuga Nadha",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "An exquisite vocal tribute chanting the dynamic, powerful six-letter name of the supreme commander.",
  },
  {
    number: 37,
    title: "Kundrathil Aadum",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Depicts the cosmic rhythm of Lord Murugan dancing on green peaks surrounded by wild peacocks.",
  },
  {
    number: 38,
    title: "Kandan Kadirovelan",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Sings of the glowing light of the Lord's spear, shining brighter than a thousand sunrays.",
  },
  {
    number: 39,
    title: "Muthukumara Swamiyey",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Invokes Lord Muthukumaran of Vaitheeswaran Koil to cure physical and mental illnesses.",
  },
  {
    number: 40,
    title: "Thanigai Valar",
    authorOrArtist: "Traditional / T.M. Soundararajan",
    genre: "tms_era",
    genreLabel: "T.M.S. Classics",
    details: "Celebrates the peaceful presence of the Lord who sits on Tiruttani Hills to soothe his warriors.",
  },

  // === SIRKAZHI GOVINDARAJAN & K.B. SUNDARAMBAL CLASSICS (41-60) ===
  {
    number: 41,
    title: "Andavan Darisaname",
    authorOrArtist: "Kannadasan / K.B. Sundarambal",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A majestic, resonant song describing the calm, simple, and profound sight of the lord at Palani.",
  },
  {
    number: 42,
    title: "Saranam Shanmuga",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A classic high-pitched submission seeking refuge in the six lotus faces of the commander of grace.",
  },
  {
    number: 43,
    title: "Muruga Muruga Endral",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Illustrates the calming power of repeating 'Muruga' when navigating severe personal crises.",
  },
  {
    number: 44,
    title: "Enna Kavi Padinalum",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A highly emotional masterpiece asking: 'No matter what poems I sing, is your heart not softening yet or opening?'",
  },
  {
    number: 45,
    title: "Thangatheril Varuvan",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Visualizes Lord Murugan arriving inside a massive, gleaming golden chariot to clear all local sorrows.",
  },
  {
    number: 46,
    title: "Vel Murugan",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A highly rhythmic, quick-tempo praise of the child who holds the pristine Spear of ultimate courage.",
  },
  {
    number: 47,
    title: "Kundram Kudi Konda",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Stresses that Lord Kumaran automatically turns every peaceful hilltop into his royal, green temple.",
  },
  {
    number: 48,
    title: "Aarumugam Aarumugam",
    authorOrArtist: "Traditional Chants / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A beautiful, rhythmic repetition of the name of the six-faced sovereign, perfect for meditation.",
  },
  {
    number: 49,
    title: "Aadanallur Ayyan",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "An ancient and rustic, highly charming village piece dedicated to the Lord of Aadanallur.",
  },
  {
    number: 50,
    title: "Thiruttani Muruganukku",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Invokes the absolute peace of Tiruttani Hills, celebrating how the lord removes all mental chaos.",
  },
  {
    number: 51,
    title: "Pachai Mayil Vahanane",
    authorOrArtist: "Traditional Bhajan / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "An incredibly sweet and popular bhajanam evoking the deep forest greens and shining blues of the divine peacock.",
  },
  {
    number: 52,
    title: "Kandanukku Vel",
    authorOrArtist: "Traditional / K.B. Sundarambal",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A high-frequency vocal storm praising the structural power and cosmic beauty of Murugan's weapon.",
  },
  {
    number: 53,
    title: "Aarumuga Swami",
    authorOrArtist: "Traditional / K.B. Sundarambal",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Invokes the sovereign of six faces to descend from the peaks of Palani Hills and wipe away tears.",
  },
  {
    number: 54,
    title: "Sivasuthaney",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Praises Lord Skanda as the ultimate child of Lord Shiva, inheriting the light of the cosmic source.",
  },
  {
    number: 55,
    title: "Kuraivondrum Illai Muruga",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Declares: 'As long as your shining Vel shields my forehead, I have absolutely zero grievances or deficits in life.'",
  },
  {
    number: 56,
    title: "Kathirvela",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Visualizes the solar-ray-like brightness of Lord Skanda's Spear cutting down the darkness of ignorance.",
  },
  {
    number: 57,
    title: "Senthil Maanagare",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A brilliant vocal tour of the scenic seashore city and temple of Tiruchendur, where waves wash the steps.",
  },
  {
    number: 58,
    title: "Mayil Vahana",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A highly soothing, deep chant to invoke peace of mind and calm frayed nerves.",
  },
  {
    number: 59,
    title: "Muruga Muruga Varuvai",
    authorOrArtist: "Traditional / K.B. Sundarambal",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "A dramatic, high-register calling requiring the immediate arrival of Lord Murugan to rescue his devotee.",
  },
  {
    number: 60,
    title: "Deiva Kavi",
    authorOrArtist: "Traditional / Sirkazhi Govindarajan",
    genre: "sirkazhi_kbs",
    genreLabel: "Sirkazhi & KBS",
    details: "Extolles how the holy verses of Saint Arunagirinathar cure all ailments when sung with correct pronunciation.",
  },

  // === PITHUKULI MURUGADAS, SULAMANGALAM & BOMBAY SISTERS (61-80) ===
  {
    number: 61,
    title: "Kanda Sashti Kavacham",
    authorOrArtist: "Bala Devaraya Swamigal / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "The world-famous protective armor shield consisting of acoustic-mantric syllables chanted daily by millions.",
  },
  {
    number: 62,
    title: "Kanda Guru Kavacham",
    authorOrArtist: "Santhananda Swamigal / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "An exceptionally powerful protection chant calling upon Murugan as our Supreme Counselor & Guru.",
  },
  {
    number: 63,
    title: "Shanmuga Kavacham",
    authorOrArtist: "Pamban Swamigal / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "A scientific high-vibrational body-armor composed by Pamban Swamigal to guard 30 specific anatomical systems.",
  },
  {
    number: 64,
    title: "Thiruchendur Kadalora Alaigalai",
    authorOrArtist: "Pithukuli Murugadas",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "An incredibly ecstatic, wave-like rhapsodic anthem imitating the ocean breeze at Senthil Velan's temple yard.",
  },
  {
    number: 65,
    title: "Nadhamenum Kovilile",
    authorOrArtist: "Pithukuli Murugadas",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "A classic non-dual exposition declaring that Murugan's true temple is built entirely out of sacred sound (Nadha).",
  },
  {
    number: 66,
    title: "Kuravalli Kaantha",
    authorOrArtist: "Pithukuli Murugadas",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "An upbeat, fast-paced folk-style track dedicated to the lord who fell in love with Valli, the forest girl.",
  },
  {
    number: 67,
    title: "Valli Kanavan Perai",
    authorOrArtist: "Traditional / Pithukuli Murugadas",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "The definitive, highly syncopated Kavadi dance song that represents the sweetest folk beats of rural Tamil Nadu.",
  },
  {
    number: 68,
    title: "Engum Niraintha",
    authorOrArtist: "Traditional / Bombay Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "A soothing omnipresence hymn praising how Skanda's spear watches and shields us in every direction.",
  },
  {
    number: 69,
    title: "Velundu Vinai Illai",
    authorOrArtist: "Traditional / Bombay Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Chants the ultimate armor motto: 'Where the Spear stands, no bad karma or negative force can ever cross our path.'",
  },
  {
    number: 70,
    title: "Saranam Saranam",
    authorOrArtist: "Traditional / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Surrenders the five active senses to the safety of Shanmuga for protection and continuous inner instruction.",
  },
  {
    number: 71,
    title: "Karthikeya Karunamoorthi",
    authorOrArtist: "Traditional / Bombay Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Invokes the stars of Karthika, who nurtured Skanda, to bring clarity of mind, intelligence, and academic focus.",
  },
  {
    number: 72,
    title: "Mayil Meethu Varuvan",
    authorOrArtist: "Traditional / Bombay Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "A cheerful harmony visualizing Lord Kandan swooping down from the skies riding his magnificent blue peacock.",
  },
  {
    number: 73,
    title: "Kandan Sharanam",
    authorOrArtist: "Traditional / Bombay Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "A soothing refuge chant bringing deep peace of mind to seekers undergoing high stress.",
  },
  {
    number: 74,
    title: "Om Muruga Natham",
    authorOrArtist: "Traditional / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Combines the ultimate primordial cosmic vibration 'Om' with the sweet, healing acoustic syllables of 'Mu-ru-ga'.",
  },
  {
    number: 75,
    title: "Sivagiri Velavan",
    authorOrArtist: "Traditional / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Dedicated to the holy hill of Sivagiri, celebrating the cosmic energy of Shiva-Skanda.",
  },
  {
    number: 76,
    title: "Thanga Mayil",
    authorOrArtist: "Traditional / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Adoring the golden peacock of Lord Kandan, bringing swift help and speed of thought near travelers.",
  },
  {
    number: 77,
    title: "Murugan Enra Peyare",
    authorOrArtist: "Traditional / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Sings of the high-vibrational, physical sweetness felt on the lips when simply declaring 'Muruga'.",
  },
  {
    number: 78,
    title: "Velan Varuvan",
    authorOrArtist: "Traditional / Sulamangalam Sisters",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "An upbeat, joyous song predicting that the Lord of Vel will definitely arrive in time to defend us.",
  },
  {
    number: 79,
    title: "Alaigal Oivathillai",
    authorOrArtist: "Pithukuli Murugadas",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "A passionate musical track stating that just like sea waves never stop, a devotee's love for Kandan never halts.",
  },
  {
    number: 80,
    title: "Valli Deivanai Sametha",
    authorOrArtist: "Pithukuli Murugadas",
    genre: "pithukuli_sisters",
    genreLabel: "Sisters & Pithukuli",
    details: "Adoring the complete form of Lord Shanmuga sitting beside his twin companions representing mind and matter.",
  },

  // === KAVADI CHINDHU, MODERN DEVOTIONAL & CARNATIC (81-100) ===
  {
    number: 81,
    title: "Chella Muthaiye",
    authorOrArtist: "L.R. Eswari",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A classic high-energy folk piece with infectious rural syncopated percussion, designed for Kavadi dancing.",
  },
  {
    number: 82,
    title: "Muthu Kumara",
    authorOrArtist: "L.R. Eswari",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A fast, joyful folk song celebrating the childhood pranks of Lord Muthukumaran.",
  },
  {
    number: 83,
    title: "Kandanin Thiruvadi",
    authorOrArtist: "P. Unnikrishnan",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A pristine, highly classical modern devotional track exploring the cool rest found at Kandan's lotus feet.",
  },
  {
    number: 84,
    title: "Varuvan Vadivelan",
    authorOrArtist: "Mahanadhi Shobana",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "An incredibly deep, emotional standard popular inside South Indian households during Sashti fasts.",
  },
  {
    number: 85,
    title: "Bhoomiyil Emathu",
    authorOrArtist: "Saint Annamalai Reddiyar / Traditional Kavadi Chindhu",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A classic Kavadi Chindu piece with syncopated, buoyant folk rhythms chanted by travelers walking on foot.",
  },
  {
    number: 86,
    title: "Chennimalai Nagar",
    authorOrArtist: "Saint Annamalai Reddiyar / Traditional Kavadi Chindhu",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "Extolles the beauty of forest wildlife, streams, and shrines surrounding Chennimalai hills.",
  },
  {
    number: 87,
    title: "Antha Valli Kanavan",
    authorOrArtist: "Pushpavanam Kuppusamy",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A playful, rustic village duet depicting Valli's forest companions and the arrival of Murugan in disguise.",
  },
  {
    number: 88,
    title: "Senthoor Vela",
    authorOrArtist: "Pushpavanam Kuppusamy",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A quick folk anthem saluting the beautiful red deity of Tiruchendur beach, washing away hard karma.",
  },
  {
    number: 89,
    title: "Muruga Muruga",
    authorOrArtist: "P. Unnikrishnan",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A highly peaceful, modern classical song composed to quieten the conscious mind.",
  },
  {
    number: 90,
    title: "Palani Andava",
    authorOrArtist: "L.R. Eswari",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "An upbeat folk anthem pleading with the lord of Palani to look down with kindness upon his simple helpers.",
  },
  {
    number: 91,
    title: "Swami Malai Vaasa",
    authorOrArtist: "Papanasam Sivan Composition / Classical Carnatic",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "Sanskrit-Tamil fusion highlighting the cool, majestic river breezes of Swamimalai hills.",
  },
  {
    number: 92,
    title: "Kaliyuga Varadan",
    authorOrArtist: "Periyasamy Thooran Composition / Classical Carnatic",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A brilliant monumental piece (Raga Brindavana Saranga) declaring Kandan as our chief Savior in this difficult era.",
  },
  {
    number: 93,
    title: "Saravana Bhava Enum",
    authorOrArtist: "Papanasam Sivan Composition / Classical Carnatic",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "Explains how the six-syllable mantra 'Sa-Ra-Va-Na-Bha-Va' heals psychological wounds (Raga Shanmukhapriya).",
  },
  {
    number: 94,
    title: "Tatvamariya Tharama",
    authorOrArtist: "Papanasam Sivan Composition / Classical Carnatic",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A masterpiece in raga Reethigowla, asking: 'How can small, dualistic minds understand your non-dual cosmic form?'",
  },
  {
    number: 95,
    title: "Sri Subramanyaya Namasthe",
    authorOrArtist: "Muthuswami Dikshitar Composition / Classical Carnatic",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "The legendary, grand Carnatic magnum opus in raga Kambhoji, showcasing majestic Sanskrit lyrics and deep phrasing.",
  },
  {
    number: 96,
    title: "Ka Vaa Vaa",
    authorOrArtist: "Papanasam Sivan Composition / Classical Carnatic",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "An extremely soulful, melting plea (Raga Varali) begging Kandan to arrive immediately and rescue the seeker.",
  },
  {
    number: 97,
    title: "Kandan Karunai Puriyum",
    authorOrArtist: "Papanasam Sivan Composition / Classical Carnatic",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A beautiful, uplifting classical song illustrating the cool comfort of Kandan's smile and presence.",
  },
  {
    number: 98,
    title: "Kandanukku Arohara",
    authorOrArtist: "Veeramani Raju",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "An upbeat, fast-paced group bhajan filled with chants of 'Arohara' supporting Kavadi dancers on their trek.",
  },
  {
    number: 99,
    title: "Velava Velava",
    authorOrArtist: "Veeramani Raju",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A high-intensity rhythmic calling of the lord of the Spear, designed to raise physical and spiritual grit.",
  },
  {
    number: 100,
    title: "Ponnar Meniyane",
    authorOrArtist: "Saint Sundarar / Traditional Devotional Bhajan",
    genre: "kavadi_carnatic",
    genreLabel: "Kavadi & Carnatic",
    details: "A supreme classical chant praising the golden-hued divine presence with sweet, heart-softening attributes.",
  }
];
